### ISSUE TITLE
Cannot install Library for Angular v12

### ISSUE THREAD

**Issue by Mavv3006** [andreymatin/scss-reset#11]
**Describe the bug**
Cannot install the library for an Angular application

**To Reproduce**
1. Create empty Angular project: `ng new ...`
2. Run `npm i scss-reset --save` in the project directory

**Expected behavior**
The library should be installed without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19043.985
 - npm v7.15.1
 - node v16.3.0
 - Angular CLI v12.0.3

**Additional context**
Log:
```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! code 1
npm ERR! path E:\Dev\Angular\scss-reset-test\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe E:\Dev\Angular\scss-reset-test\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'E:\\Dev\\Angular\\scss-reset-test\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.3.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (E:\Dev\Angular\scss-reset-test\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (E:\Dev\Angular\scss-reset-test\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (E:\Dev\Angular\scss-reset-test\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at E:\Dev\Angular\scss-reset-test\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at E:\Dev\Angular\scss-reset-test\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at E:\Dev\Angular\scss-reset-test\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (E:\Dev\Angular\scss-reset-test\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (E:\Dev\Angular\scss-reset-test\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (E:\Dev\Angular\scss-reset-test\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at E:\Dev\Angular\scss-reset-test\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at E:\Dev\Angular\scss-reset-test\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at E:\Dev\Angular\scss-reset-test\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python39\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Dev\\Angular\\scss-reset-test\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd E:\Dev\Angular\scss-reset-test\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.3.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\marvd\AppData\Local\npm-cache\_logs\2021-06-04T13_30_13_647Z-debug.log
```

**Comment by andreymatin** [comment]
Hi @Mavv3006 

Thank you for the issue. I relocated all development/test/staging resources into scss-reset-staging repository to avoid versions conflict. 

Please upgrade to version  1.2.0

**Comment by Mavv3006** [comment]
Hi @andreymatin,

Thanks for the quick fix. Works for me now.
